### ISSUE TITLE
Plugin Incompatible with TS 3.0.17?

### ISSUE THREAD

**Issue by CandiceJoy** [Armada651/g-key#9]
I have v0.6.1 of the plugin and TS 3.0.17 and the plugin doesn't load.

http://screenshots.candicejoy.com/K9pg

**Comment by CrossVR** [comment]
Looks like TeamSpeak updated their Visual C++ version. Try installing this package: http://www.microsoft.com/en-us/download/details.aspx?id=15336

**Comment by CandiceJoy** [comment]
No dice, same problem.

**Comment by thorwe** [comment]
As Ts switched from 2012 to 2013, and I think at least some recent release was compiled against 2012 (as in working in TS 3.0.16), my bet would be this redist (choose 64bit):
https://www.microsoft.com/en-us/download/details.aspx?id=30679

**Comment by CandiceJoy** [comment]
That did it!  Thanks so much!  I really love this plugin and life was getting difficult without it working xP
